### PR TITLE
Remove cvcapture files

### PR DESCRIPTION
**Pull request by RealOrangeOne**
This code moved to https://github.com/sourcebots/sb-vision

### CODE REVIEW

**Comment by PeterJCLaw** [comment]
Aha, I was wondering why we still had these around!
:+1: to removing these

**Comment by PeterJCLaw** [comment]
@RealOrangeOne have we checked that after removing these everything still works? I'm not sure how I'd really validate that, though I think the testing looks like:
- build the resulting robotd
- install that (and an sb-vision)
- check that capturing an image from the robot-api side still works

The last of these is the challenge since (as far as I know) that part doesn't work anyway at the moment.

Could you outline what if any checks you were able to do on this yesterday?

**Comment by RealOrangeOne** [comment]
@PeterJCLaw no actual testing per say, but looking through the code, the code is never used. It's missing the FFI bindings and build script. I'm confident this code hasnt actually been executed since `sb-vision` was extracted, where the file now exists.

**Review by PeterJCLaw — APPROVED** [review]
For some reason I'd thought this was also removing apriltags too. I think that was because I was looking at a version of master pre 788d197aff1b6f955a22 and/or I had built artefacts lying around.

**Pull request merged**
